// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctmalktvrizwekserduv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0bWFsa3R2cml6d2Vrc2VyZHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MzgxNzAsImV4cCI6MjA3NjIxNDE3MH0.xl2L6Ma5sGZirqB5eJf58BKJsVCQygDfEs_utkxQlPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});